FROM mambaorg/micromamba:2.3.3

WORKDIR /ogdc_runner/

# TODO: remove need to install git. Currently required because `pip install`
# initializes a local build which relies on .git to obtain version information
# (see `tool.hatch` use of vcs). I think using bump-my-version is probably
# better - this gives us tighter control over anticipated version changes.
RUN micromamba install -y pip git
COPY --chown=$MAMBA_USER:$MAMBA_USER . /ogdc_runner
RUN micromamba run pip install .[service]

EXPOSE 8000

CMD micromamba run fastapi dev --port 8000 --host 0.0.0.0 src/ogdc_runner/service.py
